---
title: "example_program"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example_program}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# CLinify will auto-load Flextable and Officer
library(clinify)
library(Tplyr)

tplyr_adsl <- tplyr_adsl %>% 
  mutate(
    SEX = recode(SEX, M = "Male", F = "Female"), 
    RACE = factor(RACE, c("AMERICAN INDIAN OR ALASKA NATIVE", "ASIAN", "BLACK OR AFRICAN AMERICAN", 
                          "NATIVE HAWAIIN OR OTHER PACIFIC ISLANDER", "WHITE", "MULTIPLE"))
  )

t <- tplyr_table(tplyr_adsl, TRT01P) %>% 
  add_layer(name = 'Sex', 
    group_count(SEX, by = "Sex n (%)") %>% 
      set_missing_count(f_str('xx', n), Missing=NA, denom_ignore=TRUE)
  ) %>% 
  add_layer(name = 'Age',
    group_desc(AGE, by = "Age (Years)")
  ) %>% 
  add_layer(name = 'Age group', 
    group_count(AGEGR1, by = "Age Categories n (%)") %>% 
      set_missing_count(f_str('xx', n), Missing=NA, denom_ignore=TRUE)
  ) %>% 
  add_layer(name = 'Race', 
    group_count(RACE, by = "Race n (%)") %>% 
      set_missing_count(f_str('xx', n), Missing=NA, denom_ignore=TRUE) %>% 
      set_order_count_method("byfactor")
  ) %>% 
  add_layer(name = 'Ethnic', 
    group_count(ETHNIC, by = "Ethnicity n (%)") %>% 
      set_missing_count(f_str('xx', n), Missing=NA, denom_ignore=TRUE)
  )

dat <- build(t) %>% 
  mutate(
    across(starts_with('var'),
    ~ if_else(
      ord_layer_index %in% c(1, 3:5),
      apply_conditional_format(
        string = .,
        format_group = 2,
        condition = x == 0,
        replacement = ""
      ),
      .
      )
    )
  )

dat <- dat %>% 
  arrange(ord_layer_index, ord_layer_1, ord_layer_2) %>% 
  apply_row_masks(row_breaks = TRUE) %>% 
  select(
    starts_with("row_label"), var1_Placebo, `var1_Xanomeline Low Dose`,
    `var1_Xanomeline High Dose`
    )

header_n <- t$header_n$n
names(header_n) <- t$header_n$TRT01P

# This is a process we want to streamline with function to make it much easier
column_headers <- data.frame(
  col_keys = names(dat),
  # This a workaround right now but the space in the third row is to make sure
  # that the rows merge, which breaks thigns when the columns merge - this will
  # have to be fixed in the default header styling
  top_row = c("", "", " ", "Xanomeline", "Xanomeline"), 
  bottom_row = c("", "", 
  sprintf('Placebo\n(N=%s)', header_n['Placebo']),
  sprintf('Low Dose\n(N=%s)', header_n["Xanomeline Low Dose"]),
  sprintf('High Dose\n(N=%s)', header_n["Xanomeline High Dose"])
))

ct <- clintable(dat) %>% 
  set_header_df(mapping = column_headers, key="col_keys") %>% 
  table_style_default() %>% 
  width(j = 1:2, width = c(2.5, 1.5)) %>%
  # ...and for the data columns.
  width(
    j = 3:ncol(dat), 
    width = get_col_widths(
    dat, lbl_width = c(2.5, 1.5), 
    num_data_cols = ncol(dat)-2)
  ) %>% 
  align(
    j = 3:5,
    align = "center",
    part = "all"
  )

ct <- ct %>% 
  # Add titles here is using new_header_footer to allow flextable functions
  # to customize the titles block
  clin_add_titles(
    ft = new_title_footnote(
        list(
          # We'll add tools to automate paging
          c("Protocol: CDISCPILOT01", "Page X of Y"),
          c("Table 14-2.01"),
          c("Summary of Demographic and Baseline Characteristics")
        ),
        "titles"
      ) %>% 
      header_style_default()
  ) %>% 
  clin_add_footnotes(
    ft = new_title_footnote(
      list(
        c(
          "Source: /my/file/path.R", 
          format(Sys.time(), "%H:%M %A, %B %d, %Y")
        )
      ),
      "footnote"
    ) %>% 
      footer_style_default() 
  )

ct
```
